version: '3.8'

services:
  web:
    build: .
    container_name: gpp-flask
    expose:
      - "5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=0
      - SECRET_KEY=${SECRET_KEY:-change-this-in-production}
      - SECURITY_PASSWORD_SALT=${SECURITY_PASSWORD_SALT:-change-this-in-production}
      - MAIL_SERVER=smtp.gppalanpur.in
      - MAIL_PORT=587
      - MAIL_USE_TLS=True
      - MAIL_USERNAME=noreply@gppalanpur.in
      - MAIL_PASSWORD=${MAIL_PASSWORD:-your-email-password}
      - DATABASE_URL=sqlite:///app.db
    volumes:
      - ./uploads:/app/uploads
      - ./app.db:/app/app.db
    restart: unless-stopped
    networks:
      - npm-network

  nginx:
    image: nginx:alpine
    container_name: gpp-flask-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - npm-network

networks:
  npm-network:
    external: true
