"""Add student fields to User model

Revision ID: 3c88eaf143ae
Revises: 2102d212ae69
Create Date: 2025-04-05 23:40:33.017408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c88eaf143ae'
down_revision = '2102d212ae69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('semester', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('branch', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_user_student_id', ['student_id'])
        batch_op.create_unique_constraint('uq_user_enrollment_number', ['enrollment_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_enrollment_number', type_='unique')
        batch_op.drop_constraint('uq_user_student_id', type_='unique')
        batch_op.drop_column('branch')
        batch_op.drop_column('semester')
        batch_op.drop_column('student_id')
        batch_op.drop_column('enrollment_number')

    # ### end Alembic commands ###
