"""Add project fair fields

Revision ID: 833730534841
Revises: 8df60efc3e66
Create Date: 2025-03-28 21:30:52.359033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833730534841'
down_revision = '8df60efc3e66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('presentation_type', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('semester', sa.String(length=20), nullable=True))
    op.add_column('projects', sa.Column('faculty_mentor', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('mobile_number', sa.String(length=15), nullable=True))
    op.add_column('projects', sa.Column('submission_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'submission_timestamp')
    op.drop_column('projects', 'mobile_number')
    op.drop_column('projects', 'faculty_mentor')
    op.drop_column('projects', 'semester')
    op.drop_column('projects', 'presentation_type')
    # ### end Alembic commands ###
