"""Initial migration with SSIP fields

Revision ID: 879b480a4c08
Revises: 
Create Date: 2025-04-05 13:23:08.566763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879b480a4c08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hod_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hod_id'], ['user.id'], name='fk_department_hod'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('fs_uniquifier', sa.String(length=255), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], name='fk_user_approver'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='fk_user_department'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fs_uniquifier')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('group_leader', sa.String(length=100), nullable=True),
    sa.Column('members', sa.Text(), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('presentation_type', sa.String(length=50), nullable=True),
    sa.Column('semester', sa.String(length=20), nullable=True),
    sa.Column('faculty_mentor', sa.String(length=100), nullable=True),
    sa.Column('mobile_number', sa.String(length=15), nullable=True),
    sa.Column('submission_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='fk_project_department'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name='fk_project_student'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('exam_id', sa.String(length=20), nullable=True),
    sa.Column('exam_type', sa.String(length=20), nullable=True),
    sa.Column('exam_name', sa.String(length=100), nullable=True),
    sa.Column('declaration_date', sa.Date(), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('institute_code', sa.String(length=20), nullable=True),
    sa.Column('institute_name', sa.String(length=100), nullable=True),
    sa.Column('course_name', sa.String(length=100), nullable=True),
    sa.Column('branch_code', sa.String(length=10), nullable=True),
    sa.Column('branch_name', sa.String(length=100), nullable=True),
    sa.Column('total_credits', sa.Float(), nullable=True),
    sa.Column('total_grade_points', sa.Float(), nullable=True),
    sa.Column('sgpa', sa.Float(), nullable=True),
    sa.Column('result_status', sa.String(length=20), nullable=True),
    sa.Column('subject_results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_results_student_id'), ['student_id'], unique=False)

    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='fk_roles_users_role'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_roles_users_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_results_student_id'))

    op.drop_table('results')
    op.drop_table('projects')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('departments')
    # ### end Alembic commands ###
