"""Add workflow relationship to SSIPSubmission

Revision ID: b9884c321d7a
Revises: 89be5873935a
Create Date: 2025-04-06 21:03:44.523086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9884c321d7a'
down_revision = '89be5873935a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ssip_submissions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_enrollment_number', type_='unique')
        batch_op.drop_constraint('uq_user_student_id', type_='unique')
        batch_op.drop_column('enrollment_number')
        batch_op.drop_column('student_id')
        batch_op.drop_column('semester')
        batch_op.drop_column('branch')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('semester', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('enrollment_number', sa.VARCHAR(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_user_student_id', ['student_id'])
        batch_op.create_unique_constraint('uq_user_enrollment_number', ['enrollment_number'])

    with op.batch_alter_table('ssip_submissions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
